import React from "react";
import { AuthProvider } from "./Providers";
import "./globals.css";
import Footer from "../components/Footer";
import MainHeading from "../components/Heading";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-70vh w-80vw">
        <MainHeading />
        <AuthProvider>{children}</AuthProvider>
        <Footer />
      </body>
    </html>
  );
}
